### DISCUSSION TITLE
Using `vcpkg` instead of `aqt` for the Qt dep

### DISCUSSION THREAD

**Discussion by nbolton** [deskflow/deskflow#7586] [Development]
We use `aqt` to satisfy the Qt dep on Windows, but we could be using the [`qt`](https://vcpkg.io/en/package/qt) package from `vcpkg` instead.

However, there is one small problem. What about macOS? We use `aqt` on macOS instead of `brew`... why? We cannot use `brew` because it has a pre-compiled version of Qt that is only compatible with the target system, so when the CI runner is latest macOS, the compiled binary is not backward compatible with previous macOS versions. If we went with brew, we'd have to somehow downgrade the runner to the oldest macOS version we support (more than half of macOS users are not on the same macOS version as the runner), which means we'd need to run a self-hosted runner (expensive).

**Comment by sithlord48** [comment]
The ci system should use the install qt action or a system package.

**Reply by nbolton** [reply]
[Not trying to defend my decision, but]: My rationale was that I wanted to align/mirror local dev env and CI as closely as possible so that we don't get different bugs in CI compared to local dev (in my experience, a problem that happens often when trying to optimize CI). Any insight on solving that issue would be a worthwhile discussion.

**Reply by sithlord48** [reply]
CI is not the same as a developers machine. Its a special case where we want specific things since we will be shipping that to ppl to use.

**Reply by nbolton** [reply]
This is very true. We definitely don't want to ship the developer environment to a customer. However, my experience tells me that it's important to be able to recreate the same conditions on a dev machine that CI creates when trying to reproduce an issue that an end-user is facing. Trying to reproduce end-user issues via CI is a nightmare in my experience.

Don't get me wrong. I'm not trying to make the two environments identical, as I know from [painful] experience that this just isn't practical to maintain. That's why our CI and dev env does differ significantly in many ways, for example:
```
config:
  windows:
    dependencies:
      # We only run `choco` when not in CI env because it's pretty unreliable and slow.
      # The Chocolatey mirror cannot be 100% reliable (according to docs) so it will often fail
      # with an error `503 (Service Unavailable: Back-end server is at capacity)` which causes
      # the nightly CI to fail intermittently.
      command-elevated: if not defined CI (choco install Chocolatey.config -y)

      # We only run `winget` when not in CI env; it's not available on the GitHub Windows runner.
      # It's simpler to solve dependencies like Ninja with a GitHub workflow action, and cmake is
      # already installed on the Windows runner.
      command: if not defined CI (winget install ninja-build.ninja cmake)
```
