### DISCUSSION TITLE
Run from inside Docker?

### DISCUSSION THREAD

**Discussion by timautin** [deskflow/deskflow#8395] [Q&A]
Hello,
I have compiled Deskflow in an Ubuntu 24.04 Docker container. I runs fine, but when I try to move my cursor to a client (having Deskflow natively installed), the cursor stays on the server. Running Deskflow natively on the server works.

Here's my docker-compose.yml:

```
services:

  deskflow:
  
    image: deskflow:latest
    build: .
    network_mode: host
    privileged: true
    
    environment:
      
      # Run GUI apps:
      - DISPLAY=${DISPLAY}
      - XDG_RUNTIME_DIR=/tmp
      
    volumes:
    
      # Run GUI apps:
      - /tmp/.X11-unix:/tmp/.X11-unix

      # Access video devices:
      - /dev:/dev
```

Is there something i need to add to grant access to the host's USB devices?

**Comment by sithlord48** [comment]
I am not sure but i wonder what do you hope to gain by running this via docker. ?

**Comment by timautin** [comment]
I'd use Deskflow in the situation I described in my other post (https://github.com/deskflow/deskflow/discussions/8396), being able to run it through Docker would allow me to ship Deskflow within my software releases and integrate it into my versioning, rather than having to install it every time I have to setup a new install.
Since the GUI launches fine and the communication with the client seems to work well, I guess I just need to add some options to my docker-compose to allow access to some device, but appart from /dev I don't know what to add. Any idea?

EDIT: another big benefit is to be able to compile on older systems by creating an up to date Docker image. For instance currently my production PCs are in Ubuntu 22.04 but Deskflow compilation guide is for Ubuntu 25 only.

**Reply by sithlord48** [reply]
>EDIT: another big benefit is to be able to compile on older systems by creating an up to date Docker image. For instance currently my production PCs are in Ubuntu 22.04 but Deskflow compilation guide is for Ubuntu 25 only.

you can just use input-leap or barrier or synergy on older systems..

i am not sure what  if any devices you may need to add. 
Gotta be able to talk over the lan the default port is 24800  need to be able to access input also not. if you find what your missing please do let us know and consider making a wiki page about it

**Comment by timautin** [comment]
Hello,

Thanks for your reply. I tried InputLeap, it doesn't detect the client (server inside Ubuntu 24.04 Docker, client running natively on macOS 15). I have to see with my employer if we can get a few Synergy licences.

In the meantime back working on Deskflow, I found that the problem comes from Wayland. When booting to an X session, I can start Deskflow from my Ubuntu 25 Docker image and it works fine :)

So I updated my Docker image to install qt6-wayland, and now when starting deskflow it starts using Wayland. However, I do not get prompted to grant input capture as I am when running natively, and this is printed in the log:

```
./deskflow-server -f --debug INFO --name LI-TAUTIN-02 --enable-crypto --address :24800 -c /root/.config/Deskflow/deskflow-server.conf --tls-cert /root/.config/Deskflow/tls/deskflow.pem
[2025-04-08T15:31:54] INFO: using ei screen for wayland
[2025-04-08T15:31:54] ERROR: failed to initialize input capture session, quitting: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files
[2025-04-08T15:31:54] NOTE: started server, waiting for clients
[2025-04-08T15:31:54] WARNING: current primary screen is not entered on shutdown
[2025-04-08T15:31:54] NOTE: stopped server
```

Googling has failed me a bit on this one, any hint?

**Reply by sithlord48** [reply]
Make sure you have an implementation of xdg-desktop-portals installed inside your container. you need both the xdg-desktop-portals as well as an implementation and you may also need proper portals on your host so docker can request access

**Comment by timautin** [comment]
Hello,

Yes thanks, indeed xdg-desktop-portals was required, as well as some env variables. Everything works now, even though I had to disable TLS encryption for the moment. If Deskflow suits our needs I'll see what I need to do to get it working.

So here's the working Dockerfile:

```
FROM ubuntu:25.04
RUN userdel -r ubuntu
ENV DEBIAN_FRONTEND=noninteractive

# --------------------------------------------------------
# Install dependencies

# Miscellaneous

RUN apt update -y && apt install --no-install-recommends -y \
        wget git cmake build-essential ninja-build \
        xorg-dev libx11-dev libxtst-dev libssl-dev \
        libglib2.0-dev libgdk-pixbuf-2.0-dev libnotify-dev \
        libxkbfile-dev qt6-base-dev qt6-tools-dev \
        libgtk-3-dev libgtest-dev libgmock-dev libpugixml-dev \
        libei-dev libportal-dev libtomlplusplus-dev libcli11-dev \
        libxcb-cursor-dev libxcb-cursor0 \
        qt6-wayland dbus-x11 \
        && rm -rf /var/lib/apt/lists/*

# --------------------------------------------------------



# --------------------------------------------------------
# Create user

ARG USERNAME=user
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN \
    groupadd --gid $USER_GID $USERNAME && \
    useradd -s /bin/bash --uid $USER_UID --gid $USER_GID -m $USERNAME && \
    apt update && \
    apt install -y sudo && \
    echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME && \
    chmod 0440 /etc/sudoers.d/$USERNAME && \
    rm -rf /var/lib/apt/lists/* && apt-get autoclean -y && apt-get autoremove -y

# Set user
USER $USERNAME
WORKDIR /home/$USERNAME

# --------------------------------------------------------



# --------------------------------------------------------
# Install Deskflow

RUN cd $HOME && \
    GIT_SSL_NO_VERIFY=true git clone https://github.com/deskflow/deskflow.git && \
    cd deskflow && \
    cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/home/user/deskflow/deskflow/6.7.0/gcc_64 && \
    cmake --build build -j8

# --------------------------------------------------------



# --------------------------------------------------------
# Setup shell & aliases:

ARG COMPUTER=YOUR-PC-NAME

SHELL ["/bin/bash", "-c"]
ENV TERM=xterm-256color
RUN echo -e "\n# Shell prompt:" >> /$HOME/.bashrc
RUN echo "PS1='\[\e]0;\u@\h: \W\a\]\[\e[0m\e[1;31m\]\u\[\e[0m\e[0;39m\]@\[\e[0m\e[1;92m\]\h\[\e[0m\e[0;39m\]:\[\e[0m\e[1;94m\]\W\[\e[0m\e[0;39m\]$ '" >> /$HOME/.bashrc

RUN echo "alias deskflow='${HOME}/deskflow/build/bin/deskflow'" >> $HOME/.bashrc
RUN echo "alias deskflow-server='${HOME}/deskflow/build/bin/deskflow-server -f --debug INFO --name ${COMPUTER} --address :24800 -c ${HOME}/.config/Deskflow/deskflow-server.conf'" >> $HOME/.bashrc

CMD bash

# --------------------------------------------------------
```

 And the corresponding docker-compose.yml:


```
services:

  deskflow:
  
    image: deskflow:latest
    build: .
    network_mode: host
    privileged: true
    
    environment:
      
      - UID=1000
      - GID=1000
      - DISPLAY=${DISPLAY}
      - WAYLAND_DISPLAY=$WAYLAND_DISPLAY

      - XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR
      - XDG_SESSION_TYPE=wayland
      - XDG_CURRENT_DESKTOP=$XDG_CURRENT_DESKTOP

      - QT_QPA_PLATFORM=wayland;xcb
      - DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
      
    volumes:
    
      - $XDG_RUNTIME_DIR/$WAYLAND_DISPLAY:$XDG_RUNTIME_DIR/$WAYLAND_DISPLAY
      - $XDG_RUNTIME_DIR:$XDG_RUNTIME_DIR

      - /tmp/.X11-unix:/tmp/.X11-unix
      - /run/user/1000:/run/user/1000
      - /dev:/dev
      - /dev/dri:/dev/dri

      - /path/to/deskflow/config/folder/on/host:/home/user/.config/Deskflow
    
    group_add:
      - video
    
    user: "1000:1000"
```

Some stuff may not be needed, I'll see later if some cleaning can be made.

Just build with `docker compose -f /path/to/docker-compose.yml --progress=plain build` and run with `docker compose -f /path/to/docker-compose.yml run --rm deskflow`

Once inside the image, the first time execute the `deskflow` alias to disable TLS encryption in prefs & configure your clients, and use the `deskflow-server` alias for next launches.

One last question, I now need to get rid of the input capture authorization popup in order to be able to restart quickly. Is that possible?
